# Generated by Django 3.1.5 on 2021-03-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=10)),
                ('post_title', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=200)),
                ('score', models.IntegerField()),
                ('publisher', models.CharField(max_length=50)),
                ('headline', models.CharField(max_length=250)),
                ('date_published', models.DateTimeField()),
                ('content', models.CharField(max_length=65000)),
            ],
        ),
    ]
