# Generated by Django 3.1.5 on 2021-03-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210317_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='article',
            name='post_title',
            field=models.CharField(max_length=400),
        ),
    ]
