# Generated by Django 3.1.5 on 2021-04-08 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_articlenlp_savedarticle_topiclkp'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiclkp',
            name='topic_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlenlp',
            name='topic',
            field=models.ForeignKey(db_column='topic', on_delete=django.db.models.deletion.CASCADE, to='news.topiclkp', to_field='topic_id'),
        ),
    ]
