# Generated by Django 3.1.5 on 2021-06-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210413_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlenlp',
            name='keywords',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
