# Generated by Django 3.1.5 on 2022-03-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_articlenlp_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlenlp',
            name='keywords',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
