# Generated by Django 3.1.5 on 2022-03-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20220323_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
